project:
  type: book

book:
  title: "Desarrollo Web FontEnd"
  author: "T.S. Christopher Jara"
  date: "2024/09/25"
  chapters:
    - index.qmd
    - 1_Capitulo.qmd
    - intro.qmd
    - summary.qmd
    - references.qmd

bibliography: references.bib

format:
  html:
    theme: superhero
  pdf:
    documentclass: scrreprt



