# Bienvenida {.unnumbered}

¡Bienvenido al Curso de Desarrollo Web, diseñado para los estudiantes de tercero de bachillerato de la U.E.P. “Carlos Crespi II, cursantes de la materia de Desarrollo Web, especialidad Informática.

En este curso, exploraremos todo, desde los fundamentos, revisando las herramientas de última tecnología, hasta las aplicaciones prácticas.

## **¿De qué trata este curso?**

Durante este periodo lectivo, cursaremos fundamentos teóricos básicos de la programación hasta la construcción de sitios web completos utilizando los lenguajes de programación HTML, CSS y JavaScript.

A través de una combinación de teoría y ejercicios prácticos, nos sumergiremos en los conceptos esenciales del desarrollo web y avanzaremos hacia la creación de proyectos del mundo real, con clientes reales, mismos que aportaran con su retroalimentación, con lo que cada proyecto se convertirá en una experiencia única.

Juntos recorreremos desde la configuración del entorno de desarrollo hasta la construcción de un sitio web de pila completa, el conocimiento que el estudiante adquirirá le proporcionará una comprensión sólida y experiencia para implementarla en proyectos en el mundo laboral real.

## **¿Para quién es este curso?**

Este curso está diseñado para estudiantes de la U.E.P. “Carlos Crespi II” principiantes en el mundo del desarrollo web, pero expertos en el diseño de sus entornos y para aquellos con poca o ninguna experiencia en programación.

Ya sea un estudiante curioso, un profesional que busca cambiar de carrera o simplemente alguien que quiere aprender desarrollo web, este documento es para usted. Desde adolescentes hasta adultos, todos son bienvenidos a participar y explorar el emocionante mundo del desarrollo web.

## **¿Cómo contribuir?**

Valoramos su contribución a este curso. Si encuentra algún error, desea sugerir mejoras o agregar contenido adicional, me encantaría saber de usted.

Puede contribuir a través del repositorio en línea, donde puede compartir sus comentarios y sugerencias.

Juntos, podemos mejorar continuamente este recurso educativo para beneficiar a la comunidad de estudiantes y entusiastas de la programación.

Este ebook ha sido creado con el objetivo de proporcionar acceso gratuito y universal al conocimiento.

Estará disponible en línea para cualquier persona, sin importar su ubicación o circunstancias, para acceder y aprender a su propio ritmo.

Puede descargarlo en formato PDF, Epub o verlo en línea en cualquier momento y lugar.

Esperamos que disfrute este emocionante viaje de aprendizaje y descubrimiento en el mundo del desarrollo web.

## **Contribución estudiantil**

Valoro mucho la dedicación que cada uno asigna a su formación profesional, y ante todas las cosas fomento la lectura, conocedor de la ajetreada vid estudiantil que los cursantes de tercero de bachillerato experimentan en este periodo lectivo, es por esta razón que; si en algún momento, uno de mis estudiantes genera contenido de valor y aporta a este documento, su esfuerzo será reconocido académicamente:

| Aporte                                | Recompensa | Insumo              |
|---------------------------------------|------------|---------------------|
| Aporte de corrección ortográfica      | 0.25       | Insumo 1            |
| Aporte de corrección de arquitectura  | 1          | Insumo 1            |
| Aporte con un texto para el documento | 1          | Proyecto Quimestral |

Entonces, a partir de este momento, si un estudiante quisiera ganar puntos adicionales en el trimestre, o quizas, con mucho esfuezo, ni siquiera presentar el proyecto final de cada trimestre, lo único que debe hacer es seguir los pasos antriores e informar en clases o realizando un pull.